
sudo: required

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

services:
  - redis-server

addons:
  apt:
    sources:
      - deadsnakes

    packages:
      - python2.7
      - python2.7-dev
      - nginx
      - realpath
      - lftp

# Separate different test suites
env:
  global:
    - PLUGIN_NAME=Organisations
    - PIWIK_ROOT_DIR=$TRAVIS_BUILD_DIR/piwik
    - PIWIK_REPOSITORY_SLUG=PiwikPRO/piwik.git
    - PIWIK_LATEST_STABLE_TEST_TARGET=3.x-pro
  matrix:
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_LATEST_STABLE_TEST_TARGET

sudo: required

script: $PIWIK_ROOT_DIR/tests/travis/travis.sh

install:
  # move all contents of current repo (which contains the plugin) to a new directory
  - mkdir $PLUGIN_NAME
  - cp -R !($PLUGIN_NAME) $PLUGIN_NAME
  - cp -R .git/ $PLUGIN_NAME/
  - cp .travis.yml $PLUGIN_NAME
  # checkout piwik in the current directory
  - git clone -q https://$GITHUB_USER_TOKEN:@github.com/$PIWIK_REPOSITORY_SLUG piwik
  - cd piwik
  - git fetch -q --all
  - sed -i "s/git@github.com:/https:\/\/$GITHUB_USER_TOKEN:@github.com\//" .gitmodules
  - git submodule init
  - git submodule update

  # make sure travis-scripts repo is latest for initial travis setup
  - 'sh -c "rm -rf ./tests/travis && git clone https://$GITHUB_USER_TOKEN:@github.com/PiwikPRO/travis-scripts ./tests/travis"'
  - cd ./tests/travis ; git checkout master ; cd ../..

  - ./tests/travis/checkout_test_against_branch.sh

  - '[ "$PLUGIN_NAME" == "" ] || [ ! -f ./tests/travis/check_plugin_compatible_with_piwik.php ] || php ./tests/travis/check_plugin_compatible_with_piwik.php "$PLUGIN_NAME"'

  - ./tests/travis/configure_git.sh

  # travis now complains about this failing 9 times out of 10, so removing it
  #- travis_retry composer self-update

  - '[ "$SKIP_COMPOSER_INSTALL" == "1" ] || travis_retry composer install'

  # move plugin contents to folder in the plugins subdirectory
  - rm -rf plugins/$PLUGIN_NAME
  - mv ../$PLUGIN_NAME plugins

  # clone dependent repos
  - ./tests/travis/checkout_dependent_plugins.sh

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-rm xdebug.ini; fi

  # add always_populate_raw_post_data=-1 to php.ini
  - echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # disable opcache to avoid random failures on travis
  - echo "opcache.enable=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # make tmpfs and run MySQL on it for reasonnable performance
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo stop mysql
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo start mysql

  # print out mysql information
  - mysql --version
  - mysql -e "SELECT VERSION();"

  # configure mysql
  - mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'" # Travis default
  # try to avoid mysql has gone away errors
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 134209536;"
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"

  - mysql -e "SELECT @@sql_mode;"
  # - mysql -e "SHOW GLOBAL VARIABLES;"

  # print out more debugging info
  - uname -a
  - date
  - php -r "var_dump(gd_info());"
  - mysql -e 'create database piwik_tests;'

  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh

  - cd tests/PHPUnit

after_script:
  # change directory back to root travis dir
  - cd $PIWIK_ROOT_DIR

  # output contents of files w/ debugging info to screen
  - cat $PIWIK_ROOT_DIR/tests/travis/error.log
  - cat $PIWIK_ROOT_DIR/tmp/php-fpm.log
  - cat $PIWIK_ROOT_DIR/tmp/logs/piwik.log
  - cat $PIWIK_ROOT_DIR/config/config.ini.php

  # upload test artifacts (for debugging travis failures)
  - ./tests/travis/upload_artifacts.sh

after_success:
  - cd $PIWIK_ROOT_DIR
