language: python
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - python-pip

# Separate different test suites
env:
  global:
    - PLUGIN_NAME=Organisations
    - PIWIK_REPOSITORY_SLUG=PiwikPRO/piwik.git
    - PIWIK_LATEST_STABLE_TEST_TARGET=3.x-pro
    - DC_ARGS="-f tests/docker/docker-compose.yml -p piwik-test"
    - MYSQL_ROOT_PASSWORD=123
  matrix:
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_LATEST_STABLE_TEST_TARGET
  
before_install:
  # move all contents of current repo (which contains the plugin) to a new directory
  - mkdir $PLUGIN_NAME
  - cp -R !($PLUGIN_NAME) $PLUGIN_NAME
  - cp -R .git/ $PLUGIN_NAME/
  - cp .travis.yml $PLUGIN_NAME
  # checkout piwik in the current directory
  - git clone -q ssh://git@github.com/$PIWIK_REPOSITORY_SLUG piwik
  - cd piwik
  - git fetch -q --all
  - git submodule update

  # make sure travis-scripts repo is latest for initial travis setup
  - 'sh -c "rm -rf ./tests/travis && git clone ssh://git@github.com/PiwikPRO/travis-scripts ./tests/travis"'
  - cd ./tests/travis ; git checkout master ; cd ../..

  - ./tests/travis/checkout_test_against_branch.sh

  - '[ "$PLUGIN_NAME" == "" ] || [ ! -f ./tests/travis/check_plugin_compatible_with_piwik.php ] || php ./tests/travis/check_plugin_compatible_with_piwik.php "$PLUGIN_NAME"'

  # move plugin contents to folder in the plugins subdirectory
  - rm -rf plugins/$PLUGIN_NAME
  - mv ../$PLUGIN_NAME plugins

  # clone dependent repos
  - ./tests/travis/checkout_dependent_plugins.sh

install:
  - pip install awscli
  - curl -s https://raw.githubusercontent.com/PiwikPRO/cloud-TravisScripts/master/docker_login_ecr.sh | bash
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes install docker-ce
  - docker-compose --version
  - docker-compose $DC_ARGS build piwik
  - docker-compose $DC_ARGS up -d piwik
  - docker ps

before_script:
  - docker-compose $DC_ARGS exec piwik pwd
  - ./tests/docker/wait-for-it.sh
  # configure mysql
  - docker-compose $DC_ARGS exec db mysql -u root --password=$MYSQL_ROOT_PASSWORD -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'" # Travis default
  # try to avoid 'mysql has gone away' errors
  - docker-compose $DC_ARGS exec db mysql -u root --password=$MYSQL_ROOT_PASSWORD -e "SET GLOBAL wait_timeout = 36000;"
  - docker-compose $DC_ARGS exec db mysql -u root --password=$MYSQL_ROOT_PASSWORD -e "SET GLOBAL max_allowed_packet = 134209536;"
  - docker-compose $DC_ARGS exec db mysql -u root --password=$MYSQL_ROOT_PASSWORD -e "SELECT @@sql_mode;"

  - docker-compose $DC_ARGS exec piwik /bin/sh -c "su-exec devel composer install"
  - docker-compose $DC_ARGS exec piwik /bin/sh -c "su-exec devel ./vendor/bin/phing setup-tests"

script:
  - docker-compose $DC_ARGS exec piwik /bin/sh -c "su-exec devel ./vendor/bin/phpunit --configuration tests/PHPUnit/phpunit.xml ./plugins/$PLUGIN_NAME/"

after_failure:
  - docker-compose $DC_ARGS logs -t piwik

cache:
  directiories:
      - $HOME/.composer/cache
  