language: php
php:
- 5.6
- 5.5
services:
- redis-server
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.6
    - python2.6-dev
    - nginx
    - realpath
    - lftp
env:
  global:
  - PLUGIN_NAME=Organisations
  - PIWIK_ROOT_DIR=$TRAVIS_BUILD_DIR/piwik
  - PIWIK_TEST_TARGET=master
  - secure: AStCwsPev7uNuBaZxDKE3oS/iVfdkBt1A544DszUNFOjQw/Pz3vW1/giMMI9nSnMb5D7sfLLdNBIICFQqLKIkm5o6olsSTeniFYte5uPRpUPAksbiOL0DZXcm9Knlm/WaMNlhPJPZdvfd5VS1zTSvk2JEHc58fgWLvtkZdw4CUKk5sjeQaFPgdMKRPBq64fjtm+abUoFW5p8dtoi5Gzth6eu02AW9d6LfMR2LjKk+qTNRzRI7ZQUG9SNOASX1LP2TghNoNbQmuK5ODjjywmGs5rupL0VouIEKE1NNlbET7Wy/oWZLbEhcyzndGfjY3T6/eeP4oXB/skLUKyVOLnI2Yeq+mcDAy0dA8m0/+m5WkEUeBm4O8L5e8KQ2e9PgpWbWKNTPhaZ8o9vgMBGHdkxy1WdRjCjOm/knzHKamjgkx57PnZzP6vRWX7qW8UROt9KnD7hZkdU5KWq7WEzBBjW05HEn2uHFDO9tYjL+nyuMa4OAgg0llDPbtBVwdAwMHezFrbRZk9sBfe7+ttbINs5JEqatu82m7K81lVEH6JUKa5mmVYr2LraSWzD1+AynoKTFFsZJWPEmkQ51cpVCAQc5oBC/6XRUZKcEG/N+/j+EVOraLTgMfIavrUBSGBZlH2pVnWvQqQqA06uwm+DVWy2RuJjyg/chtTmQvfk9GmsPqk=
  - secure: FTW5nwxEcAKBLbzjOnFHAetfh02Drv/OvOAI4nPt6k+xg77LKM1sIIde2LFV505rjqM4FkKBcXTHV5TUXZatgNbl+A4i4E82lAfH58jK+nPuUAKUKj5HhU52hf7Ai+aTRmCntT8Bzk6unUv6RNvZP5/bWlOvkoJnYNoaFVhJphBC3pr9EBDYWWBA5lBNPKm62zaMiPbd3WtyCEjMAk4oQjYS39iefkxAoF0c8YyqEg+Zn8Mge310icVNNJ5qxxOGwlEwbUdE7USZFv7ERPsjwO889Cvvx8iBi8lJSg+8TGWpijD+ugLPzw9jo47RpoGLhNDfB1DKic24sbeOLNIv6WVgUAa5yTGZCXfzj7wZqdi4OsVJb+ayoIgvDMUgvNILubt5/+yp2NmH+ZTYhtcbVvTzU/aqn4u4DAYuu6ii7d2JtXgvJysBvw6mpc+6gWoAYRtvCdLHMVtL8uERJKPjQ75G4xI/LH3o4y/Zep1hwRzTxSiU7U0dPx7Ve+rjZ7Eibh8JoqsuNKeucfxOD15m8r9E77bvNtUS3ttPbWDdRn5bGaoFey3598/LH0X7mozHUs8NARbJ7GtOiPp5dx0AB6h4+thUuvsHkqY8pr6DhsZiEdJHysNDUqTVb59t+a6AvXP7P7LitND3tKycrnGrcatshIeWHWyLHXttMYq4kbg=
  matrix:
  - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_TEST_TARGET
  - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_CORE=minimum_required_piwik
  - TEST_SUITE=UITests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_TEST_TARGET
matrix:
  exclude:
  - php: 5.5
    env: TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_CORE=minimum_required_piwik
  - php: 5.5
    env: TEST_SUITE=UITests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_TEST_TARGET
sudo: required
script: "$PIWIK_ROOT_DIR/tests/travis/travis.sh"
before_install:
- '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && export USE_ZEND_ALLOC=0 || true'
install:
- mkdir $PLUGIN_NAME
- cp -R !($PLUGIN_NAME) $PLUGIN_NAME
- cp -R .git/ $PLUGIN_NAME/
- cp .travis.yml $PLUGIN_NAME
- git clone -q https://$GITHUB_USER_TOKEN:@github.com/PiwikPRO/piwik.git piwik
- cd piwik
- git fetch -q --all
- git submodule update
- '[ -d ./tests/travis/.git ] || sh -c "rm -rf ./tests/travis && git clone https://$GITHUB_USER_TOKEN:@github.com/PiwikPRO/travis-scripts.git
  ./tests/travis"'
- cd ./tests/travis ; git checkout master ; cd ../..
- "./tests/travis/configure_git.sh"
- '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && composer config -g -- disable-tls true ||
  true'
- '[ "$SKIP_COMPOSER_INSTALL" == "1" ] || travis_retry composer install'
- rm -rf plugins/$PLUGIN_NAME
- mv ../$PLUGIN_NAME plugins
- "./tests/travis/checkout_dependent_plugins.sh"
before_script:
- if [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-rm xdebug.ini; fi
- echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "opcache.enable=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo mkdir /mnt/ramdisk
- sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
- sudo stop mysql
- sudo mv /var/lib/mysql /mnt/ramdisk
- sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
- sudo start mysql
- mysql --version
- mysql -e "SELECT VERSION();"
- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'"
- mysql -e "SET GLOBAL wait_timeout = 36000;"
- mysql -e "SET GLOBAL max_allowed_packet = 134209536;"
- mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"
- mysql -e "SELECT @@sql_mode;"
- uname -a
- date
- php -r "var_dump(gd_info());"
- mysql -e 'create database piwik_tests;'
- "./tests/travis/prepare.sh"
- "./tests/travis/setup_webserver.sh"
- if [[ "$TRAVIS_PHP_VERSION" != 5.3* ]]; then ./tests/travis/install_phantomjs.sh;
  export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH; fi
- cd tests/PHPUnit
after_script:
- cd $PIWIK_ROOT_DIR
- cat $PIWIK_ROOT_DIR/tests/travis/error.log
- cat $PIWIK_ROOT_DIR/tmp/php-fpm.log
- cat $PIWIK_ROOT_DIR/tmp/logs/piwik.log
- cat $PIWIK_ROOT_DIR/config/config.ini.php
- "./tests/travis/upload_artifacts.sh"
after_success:
- cd $PIWIK_ROOT_DIR
